# Generated by Django 3.0.3 on 2020-02-16 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=255, verbose_name='화폐명')),
                ('symbol', models.CharField(help_text='3 ~ 5글자의 대문자 알파벳으로 이루어집니다.(e.g. BTC)', max_length=10, verbose_name='화폐 심볼')),
                ('crawl_minutely', models.BooleanField(default=True, verbose_name='분당 크롤링 여부')),
                ('crawl_hourly', models.BooleanField(default=True, verbose_name='시간당 크롤링 여부')),
                ('crawl_daily', models.BooleanField(default=True, verbose_name='일일 크롤링 여부')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
            ],
            options={
                'verbose_name': '암호화폐 정보',
                'verbose_name_plural': '암호화폐 정보 목록',
                'db_table': 'currency_infos',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_datetime', models.DateTimeField(verbose_name='기준 일시')),
                ('value_open', models.FloatField(verbose_name='시가')),
                ('value_high', models.FloatField(verbose_name='고가')),
                ('value_low', models.FloatField(verbose_name='저가')),
                ('value_close', models.FloatField(verbose_name='종가')),
                ('value_volume', models.FloatField(verbose_name='거래량')),
                ('period', models.IntegerField(verbose_name='기간(분)')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('currency', models.ForeignKey(help_text='해당 화폐 1 단위를 매수하기 위해 얼마의 KRW 가 필요한 지 기록됩니다.', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='exchange.CurrencyInfo', verbose_name='대상 화폐')),
            ],
            options={
                'verbose_name': '환율 정보',
                'verbose_name_plural': '환율 정보 목록',
                'db_table': 'exchange_rates',
            },
        ),
    ]
