# Generated by Django 2.2.10 on 2020-03-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_delete_candlechart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField(default=0, verbose_name='잔액')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='currency.Currency', verbose_name='Poloniex 암호화폐')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '지갑',
                'verbose_name_plural': '지갑 목록',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=5, verbose_name='주문유형')),
                ('status', models.CharField(choices=[('ordered', 'ordered'), ('traded', 'traded'), ('cancelled', 'cancelled')], default='ordered', max_length=10, verbose_name='상태')),
                ('price', models.FloatField(verbose_name='가격')),
                ('amount', models.FloatField(verbose_name='수량')),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='currency.CurrencyPair', verbose_name='Poloniex 화폐 페어')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문 목록',
                'db_table': 'orders',
            },
        ),
    ]
