# Generated by Django 2.2.10 on 2020-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_order_traded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, verbose_name='잔액'),
        ),
    ]
