# Generated by Django 2.2.10 on 2020-02-22 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('poloniex_id', models.IntegerField(unique=True, verbose_name='Poloniex 화폐 ID')),
                ('symbol', models.CharField(max_length=10, unique=True, verbose_name='화폐 심볼')),
                ('name', models.CharField(max_length=255, verbose_name='한글 화폐명')),
            ],
            options={
                'verbose_name': 'Poloniex 암호화폐',
                'verbose_name_plural': 'Poloniex 암호화폐 목록',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('poloniex_id', models.IntegerField(unique=True, verbose_name='Poloniex 화폐 페어 ID')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs_as_from', to='currency.Currency', verbose_name='From 화폐')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs_as_to', to='currency.Currency', verbose_name='To 화폐')),
            ],
            options={
                'verbose_name': 'Poloniex 화폐 페어',
                'verbose_name_plural': 'Poloniex 화폐 페어 목록',
                'db_table': 'currency_pairs',
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('last_trade_price', models.FloatField(verbose_name='최근 체결가')),
                ('lowest_ask', models.FloatField(verbose_name='최저 매수가')),
                ('highest_bid', models.FloatField(verbose_name='최고 매도가')),
                ('change_rate_24h', models.FloatField(verbose_name='24시간 변동율')),
                ('base_volume_24h', models.FloatField(verbose_name='24시간 기본 볼륨')),
                ('quote_volume_24h', models.FloatField(verbose_name='24시간 시세 볼륨')),
                ('market_active', models.BooleanField(verbose_name='시장 활성화 여부')),
                ('highest_trade_price_24h', models.FloatField(verbose_name='24시간 최고 체결가')),
                ('lowest_trade_price_24h', models.FloatField(verbose_name='24시간 최저 체결가')),
                ('currency_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rate', to='currency.CurrencyPair', verbose_name='Poloniex 화폐 페어')),
            ],
            options={
                'verbose_name': '실시간 시세 데이터',
                'verbose_name_plural': '실시간 시세 데이터 목록',
                'db_table': 'exchange_rates',
            },
        ),
    ]
