# Generated by Django 2.2.10 on 2020-02-23 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandleChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('chart_type', models.CharField(choices=[('full', 'full'), ('yearly', 'yearly'), ('monthly', 'monthly'), ('weekly', 'weekly'), ('daily', 'daily')], max_length=10, verbose_name='차트 유형')),
                ('anchor_datetime', models.DateTimeField(verbose_name='기준일시')),
                ('price_open', models.FloatField(verbose_name='시가')),
                ('price_high', models.FloatField(verbose_name='고가')),
                ('price_low', models.FloatField(verbose_name='저가')),
                ('price_close', models.FloatField(verbose_name='종가')),
                ('volume_base', models.FloatField(verbose_name='베이스 볼륨')),
                ('volume_quote', models.FloatField(verbose_name='쿼트 볼륨')),
                ('price_average', models.FloatField(verbose_name='평균가')),
                ('currency_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candle_charts', to='currency.CurrencyPair', verbose_name='Poloniex 화폐 페어')),
            ],
            options={
                'verbose_name': '캔들 차트 데이터',
                'verbose_name_plural': '캔들 차트 데이터 목록',
                'db_table': 'candle_charts',
            },
        ),
    ]
