# Generated by Django 2.2.10 on 2020-03-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_delete_candlechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='available_for_start',
            field=models.BooleanField(default=False, verbose_name='초기자금 선택 가능 여부'),
        ),
    ]
