# Generated by Django 2.2.10 on 2020-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_currency_available_for_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='base_volume_24h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='24시간 기본 볼륨'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='highest_bid',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='최고 매도가'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='highest_trade_price_24h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='24시간 최고 체결가'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='last_trade_price',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='최근 체결가'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='lowest_ask',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='최저 매수가'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='lowest_trade_price_24h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='24시간 최저 체결가'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='quote_volume_24h',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='24시간 시세 볼륨'),
        ),
    ]
