# Generated by Django 2.2.10 on 2020-05-16 11:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20200329_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='commission_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0005'), max_digits=8, verbose_name='수수료율'),
        ),
    ]
