# Generated by Django 2.2.10 on 2020-06-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_currencypair_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='maximum_amount_for_start',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='초기자금 최대 선택 가능 금액'),
        ),
    ]
