# Generated by Django 2.2.10 on 2020-03-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='start_amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='초기자금 금액'),
        ),
    ]
