# Generated by Django 2.2.10 on 2020-06-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200329_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='닉네임'),
        ),
    ]
